# Generated by Django 3.1.3 on 2020-11-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20200207_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=80)),
                ('dni', models.IntegerField(max_length=8)),
                ('domicilio', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(max_length=30)),
            ],
        ),
    ]
