# Generated by Django 3.1.3 on 2020-11-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('matricula', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
