# Generated by Django 3.1.3 on 2020-11-28 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20201128_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='historiaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=500)),
                ('fechaModif', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.paciente')),
            ],
        ),
    ]
