# Generated by Django 3.1.3 on 2020-11-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('descrip1', models.CharField(max_length=10)),
                ('descrip2', models.CharField(max_length=10)),
                ('descrip3', models.CharField(max_length=10)),
            ],
        ),
    ]
