# Generated by Django 3.1.3 on 2020-11-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
