# Generated by Django 3.1.3 on 2020-11-28 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_auto_20201128_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.vendedor')),
            ],
        ),
    ]
