# Generated by Django 3.1.3 on 2020-11-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='fechaModif',
            field=models.DateTimeField(),
        ),
    ]
