# Generated by Django 3.1.3 on 2020-11-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_auto_20201129_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='fechaModif',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
