# Generated by Django 3.1.3 on 2020-11-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_auto_20201129_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='distaciaLente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ladoLente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='marcoLente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descrip1',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descrip2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descrip3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nombre',
        ),
    ]
