# Generated by Django 3.1.3 on 2020-11-29 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_auto_20201129_1854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='distaciaLente',
        ),
        migrations.DeleteModel(
            name='ladoLente',
        ),
        migrations.DeleteModel(
            name='marcoLente',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='producto',
            name='paciente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapi.paciente'),
            preserve_default=False,
        ),
    ]
