# Generated by Django 3.1.3 on 2020-11-29 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_lado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='paciente',
        ),
        migrations.AddField(
            model_name='producto',
            name='lado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapi.lado'),
            preserve_default=False,
        ),
    ]
