# Generated by Django 3.1.3 on 2020-11-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_auto_20201129_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default=2, max_length=344),
            preserve_default=False,
        ),
    ]
