# Generated by Django 3.1.3 on 2020-11-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_producto_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='distancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='marco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='distancia',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapi.distancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='marco',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapi.marco'),
            preserve_default=False,
        ),
    ]
