# Generated by Django 3.1.3 on 2020-11-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_auto_20201129_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapi.estado'),
            preserve_default=False,
        ),
    ]
