# Generated by Django 3.1.3 on 2020-11-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_auto_20201130_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
    ]
