# Generated by Django 3.1.3 on 2020-11-30 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0022_remove_producto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='myapi.estado'),
            preserve_default=False,
        ),
    ]
