# Generated by Django 3.1.3 on 2020-11-30 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_producto_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.estado'),
        ),
    ]
