# Generated by Django 3.1.3 on 2020-11-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_auto_20201130_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.pago'),
        ),
    ]
