# Generated by Django 3.1.3 on 2020-12-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0026_producto_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=40)),
                ('clave', models.CharField(max_length=35)),
                ('rol', models.CharField(max_length=35)),
            ],
        ),
    ]
