# Generated by Django 3.1.3 on 2020-12-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0031_auto_20201202_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
