# Generated by Django 3.1.3 on 2020-12-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0032_pedido_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(default=3, max_length=40),
            preserve_default=False,
        ),
    ]
