# Generated by Django 3.1.3 on 2020-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0035_auto_20201203_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.CharField(default=3, max_length=30),
            preserve_default=False,
        ),
    ]
