# Generated by Django 3.1.3 on 2020-12-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0036_auto_20201203_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
